openapi: 3.0.0
info:
  title: Naos Gateway Private HTTP API
  version: 1.0.0
  description: |
    ## Naos Gateway private API
    Contains utilities for developpers
  contact:
    email: "supportnaos@forsk.com"
servers:
  - url: "/private"
tags:
  - name: async-tasks
security:
  - BasicAuth: []
  - TokenAuth: []

paths:
  /admin/async-tasks/{task_id}/result:
    get:
      tags:
        - async-tasks
      summary: ADMIN. Get task results
      operationId: get_async_task_results
      parameters:
      - $ref: '#/components/parameters/AsyncTaskIdParam'
      responses:
        "200":
          description: Task error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        "204":
          description: The task finished without errors
        "404":
          description: "Taks results not found or not ready"
      x-openapi-router-controller: gateway.controllers.admin_controller
    delete:
      tags:
        - async-tasks
      summary: ADMIN. Delete task results
      operationId: delete_async_task_results
      parameters:
      - $ref: '#/components/parameters/AsyncTaskIdParam'
      responses:
        "204":
          description: OK
      x-openapi-router-controller: gateway.controllers.admin_controller
  /admin/async-tasks:
    post:
      tags:
        - async-tasks
      summary: ADMIN. Push an async task
      operationId: post_async_task
      requestBody:
        description: Task info
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - task_name
              properties:
                task_name:
                  type: string
                kwargs:
                  type: object
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: task id
        "400":
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
      x-openapi-router-controller: gateway.controllers.admin_controller

components:
  schemas:
    ApiError:
      description: Error object
      type: object
      required:
        - status
        - detail
      properties:
        status:
          description: HTTP error code
          type: integer
          readOnly: true
        title:
          type: string
          readOnly: true
        detail:
          description: Detail concerning encountered error
          type: string
          readOnly: true
        type:
          type: string
          readOnly: true
  parameters:
    AsyncTaskIdParam:
        name: task_id
        in: path
        description: Task Id
        required: true
        schema:
          type: string
          format: uuid
        example: 490b11e9-5363-4892-a7dc-bb7d4927c2d5
  securitySchemes:
    BasicAuth:
      $ref: './external/security_schemes.yaml#/BasicAuth'
    TokenAuth:
      $ref: './external/security_schemes.yaml#/TokenAuth'
